# Generated by Django 5.2.8 on 2025-11-22 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailycollection',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='dailycollection',
            index=models.Index(fields=['employee', 'date'], name='incentives__employe_9157af_idx'),
        ),
    ]
