# Generated by Django 5.2.1 on 2025-11-23 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0003_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(db_index=True, max_length=15, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('mail_id', models.EmailField(blank=True, max_length=100)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Persons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailycollection',
            name='office_type',
            field=models.CharField(choices=[('first', 'First Office'), ('second', 'Second Office')], default='first', max_length=10),
        ),
        migrations.AddField(
            model_name='dailycollection',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailycollection',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='incentives.person'),
        ),
    ]
