# Generated by Django 5.2.1 on 2025-11-22 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_incentive', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('half_day_cuts', models.IntegerField(default=0)),
                ('total_working_days', models.IntegerField(default=0)),
                ('total_present_days', models.IntegerField(default=0)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('breakdown', models.JSONField(default=dict, help_text='Detailed salary breakdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Salaries',
                'ordering': ['-end_date'],
            },
        ),
    ]
